/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author bedhu
 */
public class v_homeSupervisor extends javax.swing.JFrame {

    /**
     * Creates new form v_home
     */
    public v_homeSupervisor() {
        initComponents();
    }

    public JButton logoutButton() {
        return logout;
    }

    public JButton akunButton() {
        return akun;
    }

    public JButton stokObatButton() {
        return stok_obat;
    }

    public JButton transaksiButton() {
        return transaksi;
    }

    public JButton prediksiButton() {
        return prediksi;
    }

    public JButton permintaanButton() {
        return permintaan;
    }

    public void message(String message) {
        JOptionPane.showMessageDialog(null, message);
    }

    public int messageYesNo(String message) {
        int result = JOptionPane.showConfirmDialog(null, message, null, JOptionPane.YES_NO_OPTION);
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        permintaan = new javax.swing.JButton();
        akun = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        prediksi = new javax.swing.JButton();
        transaksi = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        stok_obat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        permintaan.setBorderPainted(false);
        permintaan.setContentAreaFilled(false);
        permintaan.setDefaultCapable(false);
        getContentPane().add(permintaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 360, 190));

        akun.setBorderPainted(false);
        akun.setContentAreaFilled(false);
        akun.setDefaultCapable(false);
        getContentPane().add(akun, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 100, 110));

        logout.setBackground(new java.awt.Color(51, 51, 51));
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setBorderPainted(false);
        logout.setContentAreaFilled(false);
        logout.setFocusable(false);
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 90, 90));

        prediksi.setBorderPainted(false);
        prediksi.setContentAreaFilled(false);
        getContentPane().add(prediksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 220, 150));

        transaksi.setBorderPainted(false);
        transaksi.setContentAreaFilled(false);
        getContentPane().add(transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 250, 170));

        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 210, 160));

        stok_obat.setBorderPainted(false);
        stok_obat.setContentAreaFilled(false);
        stok_obat.setFocusPainted(false);
        stok_obat.setFocusTraversalPolicyProvider(true);
        stok_obat.setRolloverEnabled(false);
        getContentPane().add(stok_obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 260, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/MenuSupervisior.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_homeSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_homeSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_homeSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_homeSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_homeSupervisor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akun;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton permintaan;
    private javax.swing.JButton prediksi;
    private javax.swing.JButton stok_obat;
    private javax.swing.JButton transaksi;
    // End of variables declaration//GEN-END:variables
}
